### ISSUE TITLE
Do I need a proxy?

### ISSUE THREAD

**Issue by Contamiply** [TheNetsky/Microsoft-Rewards-Script#101]
I have recently joined github and I do not know much about coding or command lines. When putting in my credentials without the proxy it won't allow me to run the code. I do not know how to get a proxy, can someone explain how and if there is one for free?

**Comment by xunilalala** [comment]
The issue of not being able to run the code is quite broad. Please provide detailed information.

Free proxies are often not very secure. You can search for keywords like "clash free node" to find options, but please be cautious.

**Comment by serzak51** [comment]
Normally you do not need a proxy, unless your connection have problems (if you can't go to bing whitout a proxy, search no further).
As xunilalala said, free proxies are pretty much out of the question. They are unreliable, i never managed to get a single free proxy working. 
Now if you want to use proxy but still do not want to pay, you can try to use the tor network. You need to modify the torrc file to only get end nodes in your country (else the account will be flagged) and setup http ports, and then your tor browser will act as a proxy, with one circuit per port. Note that you should only use tor on "old" accounts (lvl 2 accounts should be good), as tor traffic is still recognized, and will ban you if you try to use tor as proxy immediatly after creating the new account.

Though you should really clarify about the code problem. Do you get an error? Did you formatted the account.js properly? Do you have node.js? Whitout an error code we can't really help you, as it can come from litteraly anything

**Comment by Contamiply** [comment]
Sorry for not responding, I found a differnt repo that does not need a proxy. Thanks for helping anyways if the other one gives me more errors.

**Comment by TheNetsky** [comment]
This one does not need a proxy either. It's optional.
