### ISSUE TITLE
helo im new to this so can i ask how to run the script and all

### ISSUE THREAD

**Issue by raja089** [TheNetsky/Microsoft-Rewards-Script#104]
idk where to execute the scripts ive tried powershell and cmd but both failed

**Comment by raja089** [comment]
ive tried to execute npm i in the powershell in the source folder but it didnt recognize the comand

**Comment by raja089** [comment]
pretty much asking where to execute the script(cmd/powershell,etc?)

**Comment by TheNetsky** [comment]
You open powershell here:

> In the same folder where package.json is located. See setup instructions in the Readme.

**Comment by raja089** [comment]
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/136289431/db14a6df-3d97-4ee9-aa2c-68620dec3bd0)
i got this eror

**Comment by serzak51** [comment]
You first need to install nodejs: https://nodejs.org/en

**Comment by raja089** [comment]
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/136289431/75ef8db3-be4a-4522-812f-b3ed8b152a40)
got this instead
