### ISSUE TITLE
waiting for locator ('#sb_form_q') to be visible error 

### ISSUE THREAD

**Issue by Gigafrost** [TheNetsky/Microsoft-Rewards-Script#111]
Hello!

Quick question, bing rewards seems to work fine for me, up to the first bing search, in which it opens a new tab and types in the search correctly. after that it doesn't seem to want to continue a new search, leaving the previous tab up and throwing errors.

![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/3525107/32b271ae-ca3e-4b30-9a1c-e6e67e7e05e8)

Here's the error below. It will just loop with this error.
```
[5/24/2024, 8:25:17 AM] [PID: 30116] [LOG] [SEARCH-BING] 130 Points Remaining | Query: kelly rowland | Mobile: false
[5/24/2024, 8:26:01 AM] [PID: 30116] [LOG] [DASHBOARD-DATA] Provided page did not equal dashboard page, redirecting to dashboard page
[5/24/2024, 8:26:09 AM] [PID: 30116] [LOG] [GO-HOME] Visited homepage successfully
[5/24/2024, 8:26:11 AM] [PID: 30116] [LOG] [SEARCH-BING] 125 Points Remaining | Query: simone biles | Mobile: false
[5/24/2024, 8:26:22 AM] [PID: 30116] [ERROR] [SEARCH-BING] Search failed, An error occurred:Error: page.waitForSelector: Timeout 10000ms exceeded.
Call log:
  - waiting for locator('#sb_form_q') to be visible

[5/24/2024, 8:26:22 AM] [PID: 30116] [WARN] [SEARCH-BING] Retrying search, attempt 0/5
```

I've deleted my sessions folder, updated to the latest (ver 1.4.6 as of this post) and set headless mode to "false" to see what it's doing. It doesn't seem to make a difference in this behavior. Anything I'm missing?

Thanks a bunch for making this and for all you do!

**Comment by LearnerCode-01** [comment]
I'm having the same problem too but I'm not sure where the sessions folder is located so I haven't been able to delete that yet

**Comment by xd3stroyer1** [comment]
same here, I think Microsoft changed something maybe.. I can't contact the owner of script :(

**Comment by TheNetsky** [comment]
Unable to replicate this, worked fine today.

**Comment by LearnerCode-01** [comment]
what are you using to run the script, i'm using nodist to run the script with npm could that be affecting it?

**Comment by TheNetsky** [comment]
Just regular old Node 18 and npm 10.

**Comment by LearnerCode-01** [comment]
ok thank you

**Comment by mgrimace** [comment]
I had the same issue yesterday (May 24, 2024), but seems to be fine today (May 25, 2024). I'm guessing just some maintenance/funkiness from MS on their side.

**Comment by Gigafrost** [comment]
Mine looks to have fixed itself as well! Looks to be an issue with MS themselves and not the script. Yay! Thanks guys! I'll close this for now since I guess we figured it out!

**Comment by LearnerCode-01** [comment]
mine seems to be fixed today as well thanks for all your guys' help, i agree it was probably a ms issue

**Comment by xd3stroyer1** [comment]
> our guys' help, i agree it was probably a ms issue

it didn't work with me .. same issue idk why and when I try to search manually on bing when I type anything nothing shows up 
btw I'm using rdp, is that a problem ??

**Comment by LearnerCode-01** [comment]
i'm not too sure tbh but i think that could be the problem are you able to run the script without rdp?

**Comment by xd3stroyer1** [comment]
> i'm not too sure tbh but i think that could be the problem are you able to run the script without rdp?

I tried it now on my pc, still same error :( idk why

**Comment by LearnerCode-01** [comment]
i'm not sure what the problem could be then, i guess maybe you'll just have to wait a bit longer for ms to fix there side where you are but other then that i'm sorry idk what else could fix it

**Comment by xd3stroyer1** [comment]
> i'm not sure what the problem could be then, i guess maybe you'll just have to wait a bit longer for ms to fix there side where you are but other then that i'm sorry idk what else could fix it

how can I contact [TheNetsky](https://github.com/TheNetsky) ? ... maybe he can help me

**Comment by xd3stroyer1** [comment]
![Screenshot 2024-05-26 010346](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/161246000/db59a9a2-6ca1-4739-aee9-7a10ad7fd9cf)

**Comment by LearnerCode-01** [comment]
i don't know to be honest probably posting here is the best way to reach him

**Comment by LearnerCode-01** [comment]
> ![Screenshot 2024-05-26 010346](https://private-user-images.githubusercontent.com/161246000/333833651-db59a9a2-6ca1-4739-aee9-7a10ad7fd9cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NzQ5NzksIm5iZiI6MTcxNjY3NDY3OSwicGF0aCI6Ii8xNjEyNDYwMDAvMzMzODMzNjUxLWRiNTlhOWEyLTZjYTEtNDczOS1hZWU5LTdhMTBhZDdmZDljZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQyMjA0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2NjNmIzOTcxM2I1M2JjODBkMjNjM2FhZjJlYjk5YWY2NzViZTAzYzExZGJjZTFlY2ZhYjVhOGQzMmY4ZDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rUixQKon9Z587gtGP2LENHaFlSxMvgF1jkwJ7YAcOOA)
> 
> another problem, is that from ms ?

is that just from doing a search or running the script?

**Comment by xd3stroyer1** [comment]
> > ![Screenshot 2024-05-26 010346](https://private-user-images.githubusercontent.com/161246000/333833651-db59a9a2-6ca1-4739-aee9-7a10ad7fd9cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NzQ5NzksIm5iZiI6MTcxNjY3NDY3OSwicGF0aCI6Ii8xNjEyNDYwMDAvMzMzODMzNjUxLWRiNTlhOWEyLTZjYTEtNDczOS1hZWU5LTdhMTBhZDdmZDljZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQyMjA0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2NjNmIzOTcxM2I1M2JjODBkMjNjM2FhZjJlYjk5YWY2NzViZTAzYzExZGJjZTFlY2ZhYjVhOGQzMmY4ZDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rUixQKon9Z587gtGP2LENHaFlSxMvgF1jkwJ7YAcOOA)
> > another problem, is that from ms ?
> 
> is that just from doing a search or running the script?

both xD

**Comment by LearnerCode-01** [comment]
hmm, there could be something wrong with your browser but tbh thats just a guess

**Comment by xd3stroyer1** [comment]
> hmm, there could be something wrong with your browser but tbh thats just a guess

and btw, how many accounts I can run ? I heard that there is a limit you can just farm on 6 accounts per pc or per ip smth like that ... but I want to farm on more xD

**Comment by LearnerCode-01** [comment]
personally i've only ever used one but if they're running one after another i personally don't see why there would be a limit, but that is coming from my limited knowledge and experience with running this on one account

**Comment by xd3stroyer1** [comment]
> personally i've only ever used one but if they're running one after another i personally don't see why there would be a limit, but that is coming from my limited knowledge and experience with running this on one account

are u from US? is the script working with u ?

**Comment by LearnerCode-01** [comment]
no i'm not from the us and yes it's working for me right now but i've never used it with more than one account

**Comment by xd3stroyer1** [comment]
> no i'm not from the us and yes it's working for me right now but i've never used it with more than one account

do u have telegram or discord ? .. I wanna see the rewards that available for ur region 
US can farm about 200 ~ 400 daily I think and for first day you can farm about 400++ u can easily go lvl 2 in one day xD  .. and the important rewards are league of legends and roblox, tell me abt urs ?

**Comment by LearnerCode-01** [comment]
i just use ms rewards for xbox game pass core i think i normally get around 250-350 per day but that can fluctuate

**Comment by xd3stroyer1** [comment]
> i just use ms rewards for xbox game pass core i think i normally get around 250-350 per day but that can fluctuate

and what games are available for you ?

**Comment by LearnerCode-01** [comment]
on xbox game pass core?

**Comment by xd3stroyer1** [comment]
> on xbox game pass core?
no, on ms rewards

**Comment by LearnerCode-01** [comment]
ohhh um diablo 4 league of legends roblox sea of thieves and overwatch

**Comment by LearnerCode-01** [comment]
> ohhh um diablo 4 league of legends roblox sea of thieves and overwatch

all of the rewards for those games are their 'credits' or 'coins'

**Comment by mgrimace** [comment]
Ouch I came in to report that this is happening again today (May 26): `waiting for locator('#sb_form_q')`, please can folks not use the issue channel for chat/support for script installation? It's making this issue difficult to track/update.

**Comment by Omniphantasm** [comment]
Happening here too, only one account and running it same as I always have with no issues. Tried clearing sessions and continues.

**Comment by TheNetsky** [comment]
Interesting, I'll try to investigate. I've ran the script this morning (headless) and it had been working fine.

**Comment by Omniphantasm** [comment]
Yeah I'm not sure, sometimes it works sometimes it doesn't. It did about 5% of the desktop searches then started spitting that error out but the mobile ones finished just fine.

**Comment by TheNetsky** [comment]
> Yeah I'm not sure, sometimes it works sometimes it doesn't. It did about 5% of the desktop searches then started spitting that error out but the mobile ones finished just fine.

And what if u disable "scrollRandomResults" and/or "clickRandomResults"

**Comment by mgrimace** [comment]
> > Yeah I'm not sure, sometimes it works sometimes it doesn't. It did about 5% of the desktop searches then started spitting that error out but the mobile ones finished just fine.
> 
> And what if u disable "scrollRandomResults" and/or "clickRandomResults"

I tried disabling one and both options and no change on my end unfortunately.

**Comment by Omniphantasm** [comment]
Disabled both and still happening.

Looks like it managed to finish one search and that's it.

**Comment by TheNetsky** [comment]
> > > Yeah I'm not sure, sometimes it works sometimes it doesn't. It did about 5% of the desktop searches then started spitting that error out but the mobile ones finished just fine.
> > 
> > 
> > And what if u disable "scrollRandomResults" and/or "clickRandomResults"
> 
> I tried disabling one and both options and no change on my end unfortunately.

Can you record/see what it's trying to do with headless disabled? 
I just tried it again, it seems to be finishing just fine.

**Comment by xd3stroyer1** [comment]
> > > > Yeah I'm not sure, sometimes it works sometimes it doesn't. It did about 5% of the desktop searches then started spitting that error out but the mobile ones finished just fine.
> > > 
> > > 
> > > And what if u disable "scrollRandomResults" and/or "clickRandomResults"
> > 
> > 
> > I tried disabling one and both options and no change on my end unfortunately.
> 
> Can you record/see what it's trying to do with headless disabled? I just tried it again, it seems to be finishing just fine.

can you come anydesk and see it on my pc ? .. or I can send u rdp and try it

**Comment by TheNetsky** [comment]
Yeah... no. I'm not doing that.

**Comment by xd3stroyer1** [comment]
> Yeah... no. I'm not doing that.

Can I dm you on discord or anything ? .. I wanna ask you about something If u don't mind ofc

**Comment by xd3stroyer1** [comment]
> Yeah... no. I'm not doing that.

So, anydesk ?

**Comment by TheNetsky** [comment]
> > Yeah... no. I'm not doing that.
> 
> So, anydesk ?

I'm not remoting in your PC, in any shape or form.

**Comment by Omniphantasm** [comment]
Here, I meant to record it but streamed it to my Twitch instead lol lemme know when you're done so I can delete that VOD I'm too lazy to redo it.

https://www.twitch.tv/videos/2156730798

**Comment by TheNetsky** [comment]
Weird, it closes the main rewards page for some reason. Not sure what the cause of that is.

**Comment by xd3stroyer1** [comment]
any news guys ?

**Comment by TheNetsky** [comment]
I've been unable to replicate this after adding the timeout, it finished all it's searches without further errors. Maybe it's fixed, maybe it's something else. It's hard to replicate this issue consistently.

**Comment by nickshuttlewood** [comment]
I had this issue and solved it by setting **"doMorePromotions": false**. From what I could tell it was linked to some of the extra promotions (which are currently bugged) which cause an error when clicked and this then messed up the rest of the searches.

**Comment by Omniphantasm** [comment]
> I had this issue and solved it by setting **"doMorePromotions": false**. From what I could tell it was linked to some of the extra promotions, which are currently bugged and cause an error in the script when clicked, and this then messed up the rest of the searches somehow.

Can confirm that as of now it looks like doing this did fix it.   Failed to do the quiz but that's w/e, will update if it starts throwing that error again even with domorepromotions off.

**Comment by TheNetsky** [comment]
There are no "more promotions" in my country anymore. Meaning I cannot fix this issue, hopefully a PR can be made by someone who can debug this.

Using a VPN to create an account in a specific country is quite tedious since it requires a phone number.

**Comment by JittoJoseph** [comment]
does India have more promotions anymore?

**Comment by deeroverflow** [comment]
unfortunately still happening with latest on a fresh git clone :(

**Comment by TheNetsky** [comment]
Open a new issue and post your recording/details there
