### ISSUE TITLE
Bot retrying search in a cycle

### ISSUE THREAD

**Issue by XRominjol** [TheNetsky/Microsoft-Rewards-Script#121]
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/56791777/14b7ee26-7ab5-4b1a-bd98-479a02ec2222)

**Comment by serzak51** [comment]
manually put bing.com in the adress bar, and then accept/refuse the cookies when the pop up show up

**Comment by TheNetsky** [comment]
Show config
