### ISSUE TITLE
Doesnt work. or doesnt load page

### ISSUE THREAD

**Issue by gekkefries21** [TheNetsky/Microsoft-Rewards-Script#122]
the connection is fine because the proxy works and it can search up other things but it just  doesnt go to the bing rewards. 
it gives this error:
[6/16/2024, 9:10:29 PM] [PID: 92512] [LOG] [MAIN] Starting DESKTOP browser
[6/16/2024, 9:10:37 PM] [PID: 92512] [ERROR] [LOGIN] An error occurred:Error: page.goto: net::ERR_TUNNEL_CONNECTION_FAILED at https://rewards.bing.com/signin
Call log:
  - navigating to "https://rewards.bing.com/signin", waiting until "load"

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.14.0
![errorrr](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/106188613/9e27110c-2627-42cc-9b05-40ad35fceef2)

**Comment by gekkefries21** [comment]
btw I already tried to manually put in the URL. nothing changed to the issue or the console outcome.

**Comment by TheNetsky** [comment]
Seems like an issue with the proxy

**Comment by gekkefries21** [comment]
> Seems like an issue with the proxy

do you know which type of proxy I need and in which format it needs to be in. Would help alot.

**Comment by TheNetsky** [comment]
Proxy is up to you, the format is `http://xx.xx.xx.xx`

**Comment by gekkefries21** [comment]
> Proxy is up to you, the format is `http://xx.xx.xx.xx`

mine is like this atm. but  do I gotta change the url or sum. or the type of proxy cuz I can choose out of socks5 or https/http
![yesss](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/106188613/1d233a50-f395-4363-9caf-8a1d03676aff)

**Comment by DestroyerV** [comment]
Same problem happened to me also, Iam also using proxies which is not in https format

**Comment by TheNetsky** [comment]
I don't think non-http based proxies are supported

**Comment by gekkefries21** [comment]
> I don't think non-http based proxies are supported

I tested on both type of proxies but neither make it to work

**Comment by xunilalala** [comment]
> think non-HTTP-based proxies are not supported.
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/64685627/a6cf1f16-3578-45d8-b92f-b03b637b47f6)


## I have been using an HTTP proxy without any issues.
I suggest [gekkefries21](https://github.com/gekkefries21) open the F12 developer tools to check the network requests, as a single blank browser screenshot is not enough to deduce the problem

**Comment by DestroyerV** [comment]
@xunilalala  which proxy service are you using ? (I mean proxy provider)

**Comment by xunilalala** [comment]
> @xunilalala which proxy service are you using ? (I mean proxy provider)

https://github.com/automagenius/x-ui 

I created a basic HTTP proxy with the help of this project.
Because all my machines are on a local network, I used an unencrypted HTTP proxy. You can use an encrypted solution if needed.

**Comment by DestroyerV** [comment]
I have used bright data http proxies in this format 'http://brd.superproxy.io' and port: 22225 but it is also not working.
