### ISSUE TITLE
Support "Read to Earn"

### ISSUE THREAD

**Issue by 0vdruss** [TheNetsky/Microsoft-Rewards-Script#125]
Someone managed to implement Read to Earn on their script I'm wondering if its possible to implement it also here

https://github.com/klept0/MS-Rewards-Farmer/commit/5ebddb72b7a3aaf2a380f25988de2795769a8d6e

**Comment by TheNetsky** [comment]
It's not available in my region, hence I cannot test or debug this. Feel free to make a PR

**Comment by hmcdat** [comment]
I'm still try to develop it, will be released soon

![image](https://github.com/user-attachments/assets/35da24a0-51ca-405c-a176-c944395a4f82)

**Comment by hmcdat** [comment]
I'm still try to develop it, will be released soon
![image](https://github.com/user-attachments/assets/e29640be-8441-4e1f-bf5f-d816c89e6569)
