### ISSUE TITLE
Error while doing more promotions

### ISSUE THREAD

**Issue by Kornion** [TheNetsky/Microsoft-Rewards-Script#130]
Running on windows 11, the daily set is fine, but when doing any other thing, the bo sends errors and closes itself.
Using the latest node.js
![Capture d'écran 2024-08-06 223340](https://github.com/user-attachments/assets/0a9095ca-7acb-4d56-93f9-40c9d80c383b)

**Comment by TheNetsky** [comment]
Check what the script is doing by disabling headless

**Comment by TheNetsky** [comment]
Can you send a recording?

**Comment by JittoJoseph** [comment]
i'm getting the same thing

**Comment by Tekym1** [comment]
this is how it works for me 
https://imgur.com/a/fAUjeon

**Comment by Kornion** [comment]
yep it's exactly the same

**Comment by Tekym1** [comment]
this error disappears if you disable doMorePromotions

**Comment by Tekym1** [comment]
I think it happens because the program tries to perform tasks for the 2nd level, although the account only has the first level

**Comment by Tekym1** [comment]
I think it happens because the program tries to perform tasks for the 2nd level, although the account only has the first level
