### ISSUE TITLE
Search activity failing

### ISSUE THREAD

**Issue by SapitoSucio** [TheNetsky/Microsoft-Rewards-Script#133]
I have this options activated;
```
"scrollRandomResults": true,
"clickRandomResults": true,
```

When the clickRandom kicks in, some (disgusting) websites won't let you go back to bing.com, causing to fail and abort the whole search activity.

![image](https://github.com/user-attachments/assets/e0319e20-84ee-40d7-8418-ba680be297cb)

Maybe creating a new tab would be a good workaround for this cases ?

**Comment by TheNetsky** [comment]
Opening in a new tab is less natural behavior, you might as well just disable the random click, however I'll look into resolving the error so it continues regardless.
