### ISSUE TITLE
can't search , because getGoogleTrends() return 404

### ISSUE THREAD

**Issue by While-Shark** [TheNetsky/Microsoft-Rewards-Script#136]
https://trends.google.com/trends/api/dailytrends?geo=${geoLocale}&hl=en&ed=${formattedDate}&ns=15

can't search , because getGoogleTrends() return 404

**Comment by TheNetsky** [comment]
Works fine for me.

What happens when you visit 
https://trends.google.com/trends/api/dailytrends?geo=US&hl=en&ed=20240823&ns=15

**Comment by While-Shark** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by TheNetsky** [comment]
lol

**Comment by While-Shark** [comment]
yes, can call it now
thx :)

**Comment by While-Shark** [comment]
https://trends.google.com/trends/api/dailytrends?geo=US&hl=en&ed=20240823&ns=15
download json.txt on my desktop.
like this..
![image](https://github.com/user-attachments/assets/0b01fb11-cede-4700-a9d9-35c5f0d7f8e5)

it show time out...
![image](https://github.com/user-attachments/assets/654964d8-0809-475c-ba47-e34e04ca14a8)

**Comment by TheNetsky** [comment]
Are you using a proxy by chance?

**Comment by While-Shark** [comment]
> Are you using a proxy by chance?

i always use proxy  by V2R**Y

**Comment by TheNetsky** [comment]
Likely because of your location, iirc the request to Google aren't using the proxy, so it's likely unavailable in your region

**Comment by While-Shark** [comment]
> Likely because of your location, iirc the request to Google aren't using the proxy, so it's likely unavailable in your region

thanks your reply . 

i changed getGoogleTrends() code like this.

```
private async getGoogleTrends(geoLocale: string, queryCount: number): Promise<GoogleSearch[]> {
        const queryTerms: GoogleSearch[] = []
        let i = 0

        geoLocale = (this.bot.config.searchSettings.useGeoLocaleQueries && geoLocale.length === 2) ? geoLocale.toUpperCase() : 'US'

        this.bot.log('SEARCH-GOOGLE-TRENDS', `Generating search queries, can take a while! | GeoLocale: ${geoLocale}`)

        while (queryCount > queryTerms.length) {
            i += 1
            const date = new Date()
            date.setDate(date.getDate() - i)
            // const formattedDate = this.formatDate(date)

            try {
                const request = {
                    url: 'https://api.oioweb.cn/api/common/yiyan',
                    method: 'GET'
                }

                const response = await axios(request)

                const {content,date} = await response.data.result

                if(content){
                    queryTerms.push({
                        topic: content,
                        related: content
                    })
                }

                /*for (const topic of data.default.trendingSearchesDays[0]?.trendingSearches ?? []) {
                    queryTerms.push({
                        topic: topic.title.query.toLowerCase(),
                        related: topic.relatedQueries.map(x => x.query.toLowerCase())
                    })
                }*/

            } catch (error) {
                this.bot.log('SEARCH-GOOGLE-TRENDS', 'An error occurred:' + error, 'error')
            }
        }

        return queryTerms
    }
```

now it can work better in my region

**Comment by xiaoqiang1999** [comment]
> https://trends.google.com/trends/api/dailytrends?geo=US&hl=en&ed=20240823&ns=15 download json.txt on my desktop. like this.. ![image](https://private-user-images.githubusercontent.com/24545680/361684398-0b01fb11-cede-4700-a9d9-35c5f0d7f8e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzA4MzcsIm5iZiI6MTczMjA3MDUzNywicGF0aCI6Ii8yNDU0NTY4MC8zNjE2ODQzOTgtMGIwMWZiMTEtY2VkZS00NzAwLWE5ZDktMzVjNWYwZDdmOGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyNDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMzQxOWQ1ZTAzMDRlNmNlMGNkMGRkZDY2YzhhMzk4NmQzMGQ5YTRmNWI0ZWY2MjY5ZTIxZDdiMTgyMDAyZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fgJ4wL0d0dBjTz9zTlO6EPVBQSISSsDvNuvIyIPa91Y)
> 
> it show time out... ![image](https://private-user-images.githubusercontent.com/24545680/361684647-654964d8-0809-475c-ba47-e34e04ca14a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzA4MzcsIm5iZiI6MTczMjA3MDUzNywicGF0aCI6Ii8yNDU0NTY4MC8zNjE2ODQ2NDctNjU0OTY0ZDgtMDgwOS00NzVjLWJhNDctZTM0ZTA0Y2ExNGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAyNDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNTFkNmQ1MWJmZDIwMjZiZjBmNjZjYzQ5YzllNGI3Y2U1MWFiZWZmMTkyZDM4ZmQxNGM1NDc1NjUwMmNhNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-e77JhP_oUoxhl2T3v2HA0nZnCOfs5Hm3L4jbs5iOls)

把axios添加代理，代理到你的VPN，就不会超时了，超时的原因是没走代理访问不到Google。
然后还可以把“?geo=US”改为“?geo=HK”，获取香港的搜索关键字，相对更本地化一些。

**Comment by While-Shark** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
