### ISSUE TITLE
New here, Am getting 2 Weird error, not sure why, any help

### ISSUE THREAD

**Issue by Abdoud3vil** [TheNetsky/Microsoft-Rewards-Script#141]
Hello everyone, i am new here, started with this script yesterday, actually working cool, but sometimes i get those type of errors, 1st one is because of Proxy i am using i belive, and 2nd one for it's own, any help please ?

And by the way, why won't we open a Telegram or Discord Group, so we can discuss things there, would be much appreciated and easier for all of us, i hope we can make it ^^

here is the 1st error because of the proxy am using : 

![when using proxy](https://github.com/user-attachments/assets/adab5a85-0a10-44da-a909-957172e4d18d)

and here is the 2nd error when it reach the account number 3 in same bot ..

![error 2](https://github.com/user-attachments/assets/501435db-aa7e-4cad-b4ea-b7c1dba04c7f)

hope i get some help ♥ thanks all

my telegram : abdoudevil

**Comment by Abdoud3vil** [comment]
Bump ??

**Comment by TheNetsky** [comment]
Record please

**Comment by Abdoud3vil** [comment]
sure, i'll do that as soon as possible, trying now to fix this error related to search 

![image](https://github.com/user-attachments/assets/397e92a2-c727-4181-a258-a18bba350f01)

**Comment by TheNetsky** [comment]
Downgrade to the previous version for now

**Comment by Abdoud3vil** [comment]
1.4.8 right ?

**Comment by TheNetsky** [comment]
Yes

**Comment by Abdoud3vil** [comment]
> Yes

![image](https://github.com/user-attachments/assets/3b1596c3-116f-4cf3-a19f-cb8944cf88e7)


things looks working amazing with the 1.4.8

no more orange error, now i'll see the original proxy error how it goes and give a video about it ♥

**Comment by Abdoud3vil** [comment]
https://github.com/user-attachments/assets/eaffb79f-84da-440a-b188-06772523c4b3

Here is a video where i show a bot working with 5 accounts, the 3 first accounts without proxy, and the 2 last with proxies,

the first 3 accounts bot works fine, once it reach the proxy, it closes chrome and the bot give this error, any fix ?

**Comment by Abdoud3vil** [comment]
> Record please

I made the video before that comment, can you check it out?

**Comment by TheNetsky** [comment]
Should be fixed with 1.4.11
