### ISSUE TITLE
Get account cooldown for unusual search as downloaded new version

### ISSUE THREAD

**Issue by NevilYT** [TheNetsky/Microsoft-Rewards-Script#142]
I downloaded new version of the script and as I see new method of Desktop searching implemented like going to bing.com after searching and my theory is that that might make this unuseal activity banner to appear, I didn't have that before with old script it was working fine
![image](https://github.com/user-attachments/assets/23c9c092-9b68-4ebe-af15-b89ca0cabd11)

**Comment by TheNetsky** [comment]
Personally not had this, try the old version for now.

**Comment by NevilYT** [comment]
btw after testing find out that before using script everything is alright but after the limit is set 3 searches per 15 minutes

**Comment by TheNetsky** [comment]
Should be fine now, reverted basically to the old method, let me know if it helped.
