### ISSUE TITLE
An error occurred:TimeoutError: page.fill: Timeout 30000ms exceeded. Call log:   - waiting for locator('#i0116')

### ISSUE THREAD

**Issue by rosunad** [TheNetsky/Microsoft-Rewards-Script#145]
Two months using the script with any problem but since today I'm getting this message:

[2/9/2024, 13:36:33] [PID: 18212] [LOG] [MAIN] Bot started with 1 clusters
[2/9/2024, 13:36:33] [PID: 18212] [LOG] [MAIN-WORKER] Started tasks for account *********@gmail.com
[2/9/2024, 13:36:33] [PID: 18212] [LOG] [BROWSER] Created browser with User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0"
[2/9/2024, 13:36:33] [PID: 18212] [LOG] [MAIN] Starting DESKTOP browser
[2/9/2024, 13:37:19] [PID: 18212] [ERROR] [LOGIN] An error occurred:TimeoutError: page.fill: Timeout 30000ms exceeded.
Call log:
  - waiting for locator('#i0116')

Don't know if it could be due to a Chrome update

**Comment by TheNetsky** [comment]
Need more information, like script version. Preferably a recording of the script with headless disabled.

**Comment by rosunad** [comment]
I've tested this behaviour with version 1.4.7 and 1.4.10

With headless: false Chrome windows shows up and stuck waiting for password. If I do the login the script works fine.

**Comment by jacket430** [comment]
Hey there, 

Been having the same issue. Here's a full log of the script running. 

https://gist.github.com/jacket430/2ccfebf84e22b234939835929814484b

I could record a video if you'd like but there's not much to show, it just opens the https://rewards.bing.com/ page and hangs until all of the timeouts finish happening. Running with or without headless results in the same issue.

**Comment by TheNetsky** [comment]
Remove your email from the log, also are you using a proxy?

**Comment by jacket430** [comment]
Whoops, appreciate it. I'm not using a proxy, no.

**Comment by TheNetsky** [comment]
Should be fixed with 1.4.11 hopefully

**Comment by jacket430** [comment]
I've updated to 1.4.11 and am getting a _slightly_ different error now. [Here's](https://gist.github.com/jacket430/333af5292ef5348820165e628a285d12) a copy of the logs. It happens at the same time as this error used to happen, but instead of .fill it's .click. I can see the links on screen and can click them myself but the script doesn't seem to be able to recognize them. After those errors finish timing out, it moves on to finishing the rest of the script.
