### ISSUE TITLE
How to declare country ?

### ISSUE THREAD

**Issue by SapitoSucio** [TheNetsky/Microsoft-Rewards-Script#148]
I'm getting this

![image](https://github.com/user-attachments/assets/768f4cf3-8c78-4eca-ab01-6da12b58b91e)

I assume it's because the bot places a 'US' parameter? 

How can I change it ?

**Comment by luxcas0212** [comment]
i also have this problem, where did you put this?

**Comment by luxcas0212** [comment]
in the config.json file?

**Comment by luxcas0212** [comment]
I found it, I'll test it here too

**Comment by TheNetsky** [comment]
Are you using a proxy? It's just IP based, as far as I know.

**Comment by TheNetsky** [comment]
I don't think display language matters all that much? I think you can set it to display in whatever language you want. However it checks location by IP, since it only gives me that page if I turn on my VPN.

**Comment by luxcas0212** [comment]
here it seems to have been solved, I no longer have the error page

**Comment by luxcas0212** [comment]
I looked on reddit and people there also have this problem, it seems to be more a problem involving the rewards than the bot
