### ISSUE TITLE
Regional time on terminal and logs

### ISSUE THREAD

**Issue by Chappie18** [TheNetsky/Microsoft-Rewards-Script#15]
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/67442659/7dba3195-f62c-4092-b751-5d1588b42609)
How can the time on the terminal and logs be changed to appear in regional time?

**Comment by TheNetsky** [comment]
The date is based of your local PC's date.

**Comment by Chappie18** [comment]
i meant about the time !

**Comment by TheNetsky** [comment]
Updated in 1.2.5
