### ISSUE TITLE
2FA can't input on terminal

### ISSUE THREAD

**Issue by PororoManon** [TheNetsky/Microsoft-Rewards-Script#151]
I have 2 machine (PC and mini PC). on my MiniPC I can input the 2FA directly through terminal. but on my PC I can't do that.

on Mini PC, it will show

```
[9/14/2024, 9:04:57 AM] [PID: 3250355] [LOG] [LOGIN] Email entered successfully
[9/14/2024, 9:04:59 AM] [PID: 3250355] [LOG] [LOGIN] 2FA code required
Enter 2FA code:
459202 -> I can type this on my terminal
```

but on my PC, it will show. and wait it till out of time. 

```
[9/14/2024, 9:49:56 AM] [PID: 30052] [LOG] [LOGIN] Email entered successfully
[9/14/2024, 9:49:58 AM] [PID: 30052] [LOG] [LOGIN] Password entry failed or 2FA required
```

all I can do now is copy the session from my miniPC on my PC.

**Comment by kianfotovat** [comment]
I have experienced this as well. My workaround is to wait for the script to type and submit the username/password, then manually enter the 2FA code at the next screen. You only have ~20 seconds to do this but if you're quick it works fine.

**Comment by PororoManon** [comment]
> manually enter the 2FA code

Wow.. I don't know I can do that. just tried it, it show error load time out something but I got new sessions file, I run it again and it works.

**Comment by devallareddyb** [comment]
Is it supporting only Microsoft authenticator?
