### ISSUE TITLE
Proposal for integration with Anti detect browser.

### ISSUE THREAD

**Issue by StadnikovVlad** [TheNetsky/Microsoft-Rewards-Script#153]
Hi. I liked your script and would like to know if you would like to integrate your script with an anti detect browser? The bot would launch a browser profile via API and connect to it via Selenium and perform all tasks in it. This would reduce the number of blockings in your script, qualitatively change the fingerprint, information about the PC, etc. If you are interested, I would help you, because I work in the company of one of the best Anti Detect Browser.

**Comment by TheNetsky** [comment]
You're free to create a fork and add your desired features. However I don't have plans to add third party software to this project and rather keep it as it is.
