### ISSUE TITLE
Email already filled in when starting a new account.

### ISSUE THREAD

**Issue by NightsFall** [TheNetsky/Microsoft-Rewards-Script#161]
When switches over to the next account, the new account's email is somehow already filled into the field and it is already asked for a password, this causes the following error to occur:

```
[10/12/2024, 12:20:33 AM] [PID: 8856] [ERROR] [LOGIN] An error occurred: page.fill: Timeout 30000ms exceeded.
Call log:
  [2m- waiting for locator('#i0116')[22m
```

and the logs being spammed with the following constantly:

```
[10/12/2024, 12:20:35 AM] [PID: 9412] [LOG] [LOGIN-APP] Waiting for authorization
```
as you can see in the following screenshot the email is somehow already filled in:
![image](https://github.com/user-attachments/assets/5f67e644-91e1-4818-b45a-0cff87154109)

the way to fix this is to manually interrupt and press "Sign in with a different email" so that it can enter in the email like usual

**Comment by serzak51** [comment]
Try to delete the session folder for this account. I think what happened was that for some reason, at the first session, he could input the email but not the password (maybe incorrect password?), and saved the cookie in a state like this. Try to delete the session folder, and then check that the account connects correctly. Even if you have to do some kind of manual work, at least it will save a good cookie, and will save you from trouble for a few month

**Comment by NightsFall** [comment]
Thanks for the suggestion, this seemed to be the fix! Something probably went wrong when I tested the program which saved a faulty session.
