### ISSUE TITLE
Too Many Requests Error

### ISSUE THREAD

**Issue by NightsFall** [TheNetsky/Microsoft-Rewards-Script#162]
I often run into the error "Too Many Requests" from microsoft's side, the manual fix is refreshing after a couple of seconds/minutes, here's a screenshot:

![image](https://github.com/user-attachments/assets/435a75ac-2524-45be-a29a-3da3e2f0d73d)

A proxy might fix this but it would be nice for a feature to be added that retries the log in process after a couple of minutes

**Comment by TheNetsky** [comment]
I've not ran into this problem yet, so have not implemented a fix for it, if it happens during searching, increase the delay.

**Comment by NightsFall** [comment]
It happens when logging in, it's a rate limit from microsoft's side.

**Comment by TheNetsky** [comment]
How many accounts are you running? Also since I don't have had this myself, can you share the html? So I can look to implement an auto-refresh. Also only when logging in, not for the rest of the script?

**Comment by serzak51** [comment]
A solution that works pretty well is to first connect to the account with an IP that doesn't get this problem. The script will log the cookie, and won't need to log in again after that, even on the faulty IP

**Comment by NightsFall** [comment]
> How many accounts are you running? Also since I don't have had this myself, can you share the html? So I can look to implement an auto-refresh. Also only when logging in, not for the rest of the script?

Whenever I run into the issue again I'll send over the html, and yes it only happens when logging in, searching and all the other things work without any issues.

**Comment by NightsFall** [comment]
> A solution that works pretty well is to first connect to the account with an IP that doesn't get this problem. The script will log the cookie, and won't need to log in again after that, even on the faulty IP

I'm pretty sure this isn't an ip being faulty or being blocked by microsoft as after waiting for a couple of minutes and refreshing the page fixes it

**Comment by NightsFall** [comment]
The page source is literally just the text `Too Many Requests`

**Comment by NightsFall** [comment]
> How many accounts are you running?

10 accounts

**Comment by TheNetsky** [comment]
> > How many accounts are you running?
> 
> 10 accounts

I mean, I'm just using 1, the bot isn't really meant to be running that many, so I've never tested that either.

**Comment by devallareddyb** [comment]
> > > A solution that works pretty well is to first connect to the account with an IP that doesn't get this problem. The script will log the cookie, and won't need to log in again after that, even on the faulty IP
> > 
> > 
> > I'm pretty sure this isn't an ip being faulty or being blocked by microsoft as after waiting for a couple of minutes and refreshing the page fixes it
> 
> i had the same problem as you for a while, my experience is not to use these accounts anymore, instead create new accounts to use. as for the reason i guess when creating the account i used proxy and same browser which made the account marked, these accounts until now when i login it also says "Too many requests" lol. i am running about 60 accounts.

Wow... 60 accounts on single instance ?

**Comment by TheNetsky** [comment]
For now, this will be considered for later, not much I can do here without the html to detect when to reload the page.
