### ISSUE TITLE
increasing the global timeout 

### ISSUE THREAD

**Issue by Ishowsiuuu** [TheNetsky/Microsoft-Rewards-Script#165]
how to change the global timeout from 30000 to like atleast 60000 .. i changed the value in the config file but its not changing and my wifi is kinda slow sometimes so yea how to change it cuz most of the time at authorizing my account at the starting , the timeout limit exceeds so i want to change it 

It shows me this when that happens
![Uploading Screenshot 2023-09-03 213818.png…]()

**Comment by TheNetsky** [comment]
You can the config and rebuild, or change the config in the "dist" folder.

**Comment by weiyunkj666** [comment]
> You can the config and rebuild, or change the config in the "dist" folder.
Hello, thank you for making such a good program. I would like to ask when version 1.4.12 will be released. This is not a reminder, just a greeting.

**Comment by Ishowsiuuu** [comment]
> You can the config and rebuild, or change the config in the "dist" folder.

ok thanks it worked
