### ISSUE TITLE
 Feature Request - Browser Compatibility

### ISSUE THREAD

**Issue by Chappie18** [TheNetsky/Microsoft-Rewards-Script#17]
I would like to request the integration of alternative browsers like **Brave** in addition to Chrome. This enhancement would offer users flexibility and privacy options. Please consider this feature to enhance our browsing experience.

**Comment by TheNetsky** [comment]
I don't see the point of that, finger print is already being generated. The script has to emulate the Edge browser which it's already doing.

**Comment by Chappie18** [comment]
Indeed, the software effectively emulates the Edge browser and generates the needed fingerprint. However, the troubling element is the excessive memory utilisation! i believed using brave or other browser will solve issue

**Comment by TheNetsky** [comment]
Well, link me a maintained dependance that uses Brave instead of Chrome. It it's not too annoying to change, I might.

**Comment by Chappie18** [comment]
> Well, link me a maintained dependance that uses Brave instead of Chrome. It it's not too annoying to change, I might.

actually i tried to discover _options.binary_location = "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"_ inside your src files, but seems like codes are entirely distinct

**Comment by TheNetsky** [comment]
I mean you can't it expect that to work.
It doesn't work like that.

**Comment by Chappie18** [comment]
> I mean you can't it expect that to work. It doesn't work like that.

basically the problem is high cpu and memory utilisation and fan runs full speed if there is a method to remedy that, chrome is great i believe

**Comment by TheNetsky** [comment]
What, that's definitely something on your end, a single chrome instance does not do that. Makes sure you properly close the instance, else open task manager.

**Comment by Chappie18** [comment]
> What, that's definitely something on your end, a single chrome instance does not do that. Makes sure you properly close the instance, else open task manager.

Sure, let me double-check.
