### ISSUE TITLE
1.5 searchonbing activities not working

### ISSUE THREAD

**Issue by serzak51** [TheNetsky/Microsoft-Rewards-Script#179]
I will admit, this was an ingenious way to solve these activities. But microsoft are smarter. Putting the question inside bing never works. That's why the activity is so tricky, the way to clear these activities almost seems random, and they doesn't seems to leave any hint for it. One way that maybe, maybe we could solve this is by putting the question inside a textual AI asking it to solve the activity in some kind of way, but it comes with its own troubles (notably about api that might suddenly change for no reason, or the fact that most of them cost money)
Also you didn't add the option to disable the searchonbingactivity, so you still need to disable all "more promotions" activities to not have the script waste time on trying to do them

Also, completely unrelated, but the delay for dismissing messages is dependent of the global timeout. Problem, because i use tor, to make sure that the script doesn't just timeout because tor decide to be slow for no reason, i have a timeout of 4 minutes, meaning that the script is waiting 4 minutes for each pop-up that it's searching, so x4, which is a pretty long time.
Though this might just be a bug somewhere, because it's always saying that it found a message, even when he didn't actually found one

**Comment by TheNetsky** [comment]
I'm not sure what you mean, I've tested these, and they work, it only repeats the question if the the question is not found or has no answer in "https://github.com/TheNetsky/Microsoft-Rewards-Script/blob/main/src/functions/queries.json"

I expect people to submit a PR for these since these tend to differ per day, these are the ones I could find myself.

However when answers are provided, they do work fine.

**Comment by serzak51** [comment]
Ahh yep, for the new settings i used the default, and "searchOnBingLocalQueries" was on false by default (not sure why, shouldn't it be on true by default?)
Though it doesn't work out of the box, the queries.json isn't transfered when building, so you need to move it from the scr to the dist folder

**Comment by TheNetsky** [comment]
Because it's will a WIP, it'll be true once merged with the main branch.

**Comment by TheNetsky** [comment]
This has been fixed, if there are new "questions" that needed to be added, lmk
