### ISSUE TITLE
1.4.11: Group of activities not completed even though the script says it is

### ISSUE THREAD

**Issue by Gigafrost** [TheNetsky/Microsoft-Rewards-Script#181]
So even though it gives the "UrlReward completed successfully" message, it looks like the following activities still don't complete

- Get your shopping done faster
- Prepare for the weather
- You can track your package
- How's the economy?
- Who Won?
- Gaming time
- Find somewhere new to explore

Here's a screenshot
![image](https://github.com/user-attachments/assets/1ccb5f60-0b40-4867-b251-3f083c9a69c7)

I have the latest version 1.4.11 (I heard that there's a 1.4.12 already out but i was unable to find it, so not sure if this has been resolved already)

Any help is appreciated and as always thank you for everything you do in providing us such an amazing script!

**Comment by TheNetsky** [comment]
Other than 1.5 which is WIP those are not supported

**Comment by Gigafrost** [comment]
> Other than 1.5 which is WIP those are not supported

Gotcha thank you! You can go ahead and close this :)

**Comment by Gigafrost** [comment]
Boop!
