### ISSUE TITLE
Add a 15 minute counter every 4 searches.

### ISSUE THREAD

**Issue by rosmander** [TheNetsky/Microsoft-Rewards-Script#185]
Would it be possible to add in future versions of the script that we can configure it to make 4 searches whether they are pc or mobile, and that this on hold 15 minutes and then return to continue with the searches. There are nowadays many accounts with this limitation and the only current solution that I can think of with the script, is either to run it several times a day, or to make the loop more than 5 times. Would it be possible to add this option? I think it would be very appreciated by many. Thank you for your attention.

Translated with DeepL.com (free version)

**Comment by TheNetsky** [comment]
Why not set it to do 1 per 3 min? Same thing?

**Comment by rosmander** [comment]
I finally set the times for the searches to be done between 3 and 4 minutes so that I don't have problems and it seems to be working correctly. Thank you very much for your help.
