### ISSUE TITLE
Today it is not working for me

### ISSUE THREAD

**Issue by Juancafr** [TheNetsky/Microsoft-Rewards-Script#192]
That is the error that I get today and it doesn't do any searches or anything, the script closes

This page does not work
Rewards.bing.com is unable to process this request now.
HTTP ERROR 500

**Comment by TheNetsky** [comment]
Same here, seems to be on Bing's side, retry and eventually It'll work

**Comment by Juancafr** [comment]
I have tried many times and there is no way
