### ISSUE TITLE
Issue after logging in

### ISSUE THREAD

**Issue by Braxxa** [TheNetsky/Microsoft-Rewards-Script#20]
(https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/99509053/d9441147-f6a4-479d-b195-11ff6ea9813c)

**Comment by TheNetsky** [comment]
> (https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/99509053/d9441147-f6a4-479d-b195-11ff6ea9813c)

Update your config.json to the latest and currentt.
