### ISSUE TITLE
2FA Issue

### ISSUE THREAD

**Issue by kloklojul** [TheNetsky/Microsoft-Rewards-Script#23]
On one of my accounts i have 2FA active. The app asks me to enter a 2FA code but the 2FA for that requires to tab the displayed number  on my phone. If i do and enter nothing (or some randome stuff) the app crashes with the message that an element cannot be found.

In my opinion there should be a fallback where the app checks if the user is logged in after the 2FA stuff (e.g. logged in manualy) and than just continue with the usual workflow.

**Comment by TheNetsky** [comment]
I do not have an account with 2FA enabled, so this will not be my priority for a while.
