### ISSUE TITLE
"Clear cache on exit" configuration parameter

### ISSUE THREAD

**Issue by Chappie18** [TheNetsky/Microsoft-Rewards-Script#25]
I would really appreciate it if you could add an argument to the config to remove the cache after farming, since Chrome uses up too much session storage space after a few days. I'm attaching a photo of the options to clean

![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/67442659/bd809e4b-1869-47f0-b0ff-f4a350618569)

**Comment by TheNetsky** [comment]
Just delete the session in the session folder? Adding such config is no use. It'll log you out, at that point it's cleaner to do a complete whipe.

**Comment by Chappie18** [comment]
clearing cookies, deletes the session.
other option doesn't. 😅

**Comment by TheNetsky** [comment]
Didn't look a the image provided, however I still don't see how this would be more beneficial compared to clearing the folder.

**Comment by Chappie18** [comment]
Actually, removing the folder requires me to log in to all of my accounts again, which is problematic because numerous logins can result in account lockout, so retaining the session helps.

**Comment by TheNetsky** [comment]
I mean the folder of the session you want to remove.

**Comment by TheNetsky** [comment]
However this is not planned right now, maybe later since this is a non-issue for me personally. (And yes, this is however still a personal project at it's core)

**Comment by Chappie18** [comment]
Sure, no problems, I simply reported it when I noticed Chrome taking up a lot of space. With brave browser, you can clear cache on leaving, but with chrome, you can't, so I thought if there was a setting to clear cache on exit, it would really benefit low storage people.

**Comment by TheNetsky** [comment]
As far as I know there's no such easy setting, as least with Puppeteer. It'll likely require you to open dev tools and enter some commands.  (Unless there is a way) It can be added, but I don't see this as a priority. How ever feel free to shoot a PR.
