### ISSUE TITLE
Accounts getting banned, possible suggestion

### ISSUE THREAD

**Issue by Guido30** [TheNetsky/Microsoft-Rewards-Script#26]
Hello

Today one of my accounts that i specifically made to use with this script has been banned, so far its the third time and never got to redeem, it seems that when getting closer to 4k-6k points the accounts get banned.

My suggestion would be to add a lot more randomization in the timings and order of actions, for example, instead of always doing daily set -> promotional items -> searches, it should randomly do once of each type every time, with a random delay between each action, also when solving daily set quizes, there should be a random timer between each click on a quiz item, seems static right now.

Are you (dev) also facing the ban issues with accounts farmed with this script?

Thanks :)

**Comment by TheNetsky** [comment]
See r/MicrosoftRewards it's not just the script. The cause can be anything.

**Comment by TheNetsky** [comment]
OP mentioned "banned" so I'm going to assume he means the same thing.
