### ISSUE TITLE
Bot wont start

### ISSUE THREAD

**Issue by useflameclient** [TheNetsky/Microsoft-Rewards-Script#28]
Every time i try to open the bot, with or without proxy, it crashes.
the error (all i have in console after start):
npm run start

> microsoft-rewards-script@1.3.0 start
> node ./dist/index.js

[12/9/2023, 2:27:22 PM] [PID: 94468] [LOG] [MAIN] Bot started with 1 clusters
[12/9/2023, 2:27:22 PM] [PID: 94468] [LOG] [MAIN-WORKER] Started tasks for account XXXXXXXX@outlook.com
[12/9/2023, 2:27:23 PM] [PID: 94468] [LOG] [MAIN] Starting DESKTOP browser
[12/9/2023, 2:27:30 PM] [PID: 94468] [ERROR] [LOGIN] An error occurred:Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://rewards.bing.com/signin
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.16.0

**Comment by useflameclient** [comment]
config.json:
{
    "baseURL": "https://rewards.bing.com",
    "sessionPath": "sessions",
    "headless": false,
    "runOnZeroPoints": false,
    "clusters": 1,
    "workers": {
        "doDailySet": true,
        "doMorePromotions": true,
        "doPunchCards": true,
        "doDesktopSearch": true,
        "doMobileSearch": true
    },
    "searchSettings": {
        "useGeoLocaleQueries": false,
        "scrollRandomResults": true,
        "clickRandomResults": true,
        "searchDelay": {
            "min": 10000,
            "max": 20000
        }
    },
    "webhook": {
        "enabled": true,
        "url": "https://discord.com/api/webhooks/XXXXXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXX"
    }
}
accounts.json:
[
    {
        "email": "XXXX@outlook.com",
        "password": "XXXX",
        "proxy": {
            "url": "",
            "port": 0,
            "username": "",
            "password": ""
        }
    }
]

**Comment by TheNetsky** [comment]
And this is the same as the account/config.json in the "dist" folder?

**Comment by useflameclient** [comment]
no

**Comment by useflameclient** [comment]
should I change there to be the same?

**Comment by TheNetsky** [comment]
Is it not? It should be, else delete the "dist" folder and recompile.

**Comment by useflameclient** [comment]
alright

**Comment by useflameclient** [comment]
it might be cause i changed settings over time and didnt recompile

**Comment by useflameclient** [comment]
WORKING AS EXPECTED. W MANS

**Comment by useflameclient** [comment]
you can close now
