### ISSUE TITLE
15min search cooldown between 3 searches for points, new MS restriction

### ISSUE THREAD

**Issue by mgrimace** [TheNetsky/Microsoft-Rewards-Script#29]
MS has introduced a 15-minute cooldown between every 3 searches, see [here](https://www.reddit.com/r/MicrosoftRewards/comments/189cxl9/official_discussion_thread_recent_changes_to_the/?utm_source=share&utm_medium=web2x&context=3)

Practically speaking, the script stops earning points after 3 searches, which is showing as `[WARN] [SEARCH-BING] Search didn't gain point for 10 iterations aborting searches`. This appears to carry-over to mobile so if it stops desktop searches, mobile doesn't earn any points.

**Comment by TheNetsky** [comment]
Works fine for me this morning, seems to be only in certain countries (as of now). Whenever that is rolled out to my country I will unlikely keep using MS Rewards entirely.

**Comment by mgrimace** [comment]
Unfortunate but understandable, thanks for your work

**Comment by TheNetsky** [comment]
Also to counter your issue, maybe increase the search delay to a min of 5min and  max of 15min?

**Comment by mgrimace** [comment]
> Also to counter your issue, maybe increase the search delay to a min of 5min and max of 15min?

Thanks so much for that, as a lay-person, how/where would I make those changes? I'll test it out and report back for others just in case.

**Comment by mgrimace** [comment]
> Should be in the config.json?

Excellent, ok, I changed the search delay in the config.json to min: 5min in miliseconds and max: 15 mins in miliseconds. Then re-ran `npm run build` to rebuild the script. Here's the change for anyone else affected:

```json
        "searchDelay": {
            "min": 300000,
            "max": 900000
        }           
```

Re-running the script and it appears to be chugging along (slowly now, of course given the delay) and points are being awarded so far for searches. 

I'll report back if there's any further tweaks that need to happen or further issues. Appreciate the help!

**Comment by mgrimace** [comment]
Ok, reporting back - after a number of hours the desktop searches completed successfully. However, for whatever reason the mobile searches are stuck at 60. I'm not sure what that's all about

**Comment by CasualPlayer96** [comment]
> Ok, reporting back - after a number of hours the desktop searches completed successfully. However, for whatever reason the mobile searches are stuck at 60. I'm not sure what that's all about

I have the same problem.

**Comment by TheNetsky** [comment]
I have yet to find a solution for it.

**Comment by mgrimace** [comment]
My mobile searches were zero, but manually deleting the sessions folder then re-running the script completed them. In my region, the max mobile searches are 60.

Re. 15 min timers, is there a way to complete 3-4 searches *then* wait/delay for the 5-15 mins? That might at least cut down on some of the overall search time. No worries if not, it's working as it is with the above fixes. I use this cron:

`10 7,15 * * * cd /root/Microsoft-Rewards-Script && rm -rf ./dist/browser/sessions && npm run start`

**Comment by TheNetsky** [comment]
Uhm. 1.4.0 fixed mobile searches. 15min timers are per region and I will not account for those. If you have issues with that you'll gave to make your own changes.

**Comment by mgrimace** [comment]
> Uhm. 1.4.0 fixed mobile searches. 15min timers are per region and I will not account for those. If you have issues with that you'll gave to make your own changes.

Completely understandable, I don’t have the scripting skills (just good at copy/paste) but that’s on me, and I appreciate your work. Re. Mobile searches that’s strange, I’ll retry, I was getting 0 even with the 1.4.0 and deleting the session ‘lock’ fixed it for me.

**Comment by TheNetsky** [comment]
Well as per 1.4.0 you should delete everything when installing 1.4.0.

**Comment by mgrimace** [comment]
I'm doing some very informal testing on the delay ranges to avoid the cooldown while minimizing the time needed to run the script in full. As far as I can tell, the following works for me:

**New**
```yaml
        "searchDelay": {
            "min": 180000,
            "max": 270000
        },
```
which equates to a range of 3-4.5 minutes per search, which in turn gives a range of 12-18 minutes for every 4 searches. At least one full run of this did not trigger a stop/cooldown/abort. I had previously had it set at 5-15 minutes _per search_ and was able to cut things down:

**Old**
```yaml
        "searchDelay": {
            "min": 300000,
            "max": 900000
        },
```

Posting this here in case any other folks are in a country with a cooldown period timer to hopefully shave some time off.

**Comment by NevilYT** [comment]
is this limit forever or it is temperory

**Comment by Juancafr** [comment]
Is there a risk in having a script per account and running them all at once? For those of us who have multiple accounts, it takes less time than if we use the same script for all of them.

**Comment by zubtr** [comment]
Para evitar los ban de tiempo 15 minutos y restricciones a la hora de canjear. Lo mejor es prepara el bot para que la IA de Google cree en cada ejecución del bot un texto con preguntas lógicas a usar, ejm. Composición del agua, vida en la selva, construcción de barcos,etc. Por qué parece que las busquedas de Google trend están señaladas como bots
