### ISSUE TITLE
Mobile searches not completing

### ISSUE THREAD

**Issue by TheNetsky** [TheNetsky/Microsoft-Rewards-Script#31]
Remains stuck on 60 points remaining.

**Comment by cmulittlechild** [comment]
oh,really? let me see see

**Comment by TheNetsky** [comment]
Yea, I've tried doing other user agents, fingerprints etc. So I'll have to take a better look at what's causing it. Or someone else can.

**Comment by cmulittlechild** [comment]
> Yea, I've tried doing other user agents, fingerprints etc. So I'll have to take a better look at what's causing it. Or someone else can.

yes, i found it too. i can get a mobile false on console. i currently come to same stubborn, stuck at 60 points. But i don't know how to fix it, call for owner！
<img width="570" alt="EB43D14B-55E9-4A07-93CE-AF4D8F098E7E" src="https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/31565938/b158f0cc-0a4a-463b-8e19-79cd2dde5856">

**Comment by TheNetsky** [comment]
> > Yea, I've tried doing other user agents, fingerprints etc. So I'll have to take a better look at what's causing it. Or someone else can.
> 
> yes, i found it too. i can get a mobile false on console. i currently come to same stubborn, stuck at 60 points. But i don't know how to fix it, call for owner！ <img alt="EB43D14B-55E9-4A07-93CE-AF4D8F098E7E" width="570" src="https://private-user-images.githubusercontent.com/31565938/293601638-b158f0cc-0a4a-463b-8e19-79cd2dde5856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNDAwMjksIm5iZiI6MTcwNDEzOTcyOSwicGF0aCI6Ii8zMTU2NTkzOC8yOTM2MDE2MzgtYjE1OGYwY2MtMGE0YS00NjNiLThlMTktNzljZDJkZGU1ODU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDIwMDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwODdjZDM1NWYyY2IzNjdlZWJhYWU5MTY0MjBjY2RmOTg4NTY4NThiYzk2NjQ1MjQ0NWIyZTgxZmRlODA0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WA7oaxbx7D77XKzlmIPMrAATSbL9nIVUN_Bs4WB0pSQ">

What? I'm the owner of this repo, I made this issue as a reminder to myself and those who came to report it. Maybe someone else knows the solution to this.

**Comment by cmulittlechild** [comment]
> > > Yea, I've tried doing other user agents, fingerprints etc. So I'll have to take a better look at what's causing it. Or someone else can.
> > 
> > 
> > yes, i found it too. i can get a mobile false on console. i currently come to same stubborn, stuck at 60 points. But i don't know how to fix it, call for owner！ <img alt="EB43D14B-55E9-4A07-93CE-AF4D8F098E7E" width="570" src="https://private-user-images.githubusercontent.com/31565938/293601638-b158f0cc-0a4a-463b-8e19-79cd2dde5856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNDAwMjksIm5iZiI6MTcwNDEzOTcyOSwicGF0aCI6Ii8zMTU2NTkzOC8yOTM2MDE2MzgtYjE1OGYwY2MtMGE0YS00NjNiLThlMTktNzljZDJkZGU1ODU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDIwMDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwODdjZDM1NWYyY2IzNjdlZWJhYWU5MTY0MjBjY2RmOTg4NTY4NThiYzk2NjQ1MjQ0NWIyZTgxZmRlODA0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WA7oaxbx7D77XKzlmIPMrAATSbL9nIVUN_Bs4WB0pSQ">
> 
> What? I'm the owner of this repo, I made this issue as a reminder to myself and those who came to report it. Maybe someone else knows the solution to this.

oh sorry i'm blind. i worked on it yesterday, i found  it may have problems on detecting whether desk task is over. i mean we need a better method to change  one to another. Or we could just ignore getting the remaining points, every minute run desk and mobile once lasting two hours or more which i think is enough. we can just get the remaining points after running one hour but not getting it every task, you know doing more makes more mistake, just simplify it. 
Additionly, i add proxy on it and it works well especially this bug. 
thanks for your job, bro.

**Comment by TheNetsky** [comment]
It just errors and moves on to the next, so it doesn't matter. Also Desktop searches work fine, it's like I said explicitly the Mobile searches. In your screenshot you're showing Desktop searches. So not sure what you mean here.

**Comment by cmulittlechild** [comment]
ok, I come here again, could you help me? change the google trends to https://top.baidu.com/board?tab=realtime ? Coz I can't use google, I am so sad, I try to do it by my self, but it did't work. I can only change it with python, I type it below, It will be very nice if you can help me, please~
```
def getGoogleTrends(self, wordsCount: int) -> list:
        searchTerms = []

        r = requests.get('https://top.baidu.com/board?tab=realtime')

        soup = BeautifulSoup(r.text, 'html.parser')

        trending_elements = soup.find_all('div', class_='c-single-text-ellipsis')

        for element in trending_elements:
            searchTerms.append(element.text.strip().lower())

        searchTerms = searchTerms[:wordsCount]

        return searchTerms
```

**Comment by TheNetsky** [comment]
No, also stop posting on this issue. It's unrelated.

**Comment by melionor** [comment]
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/78068969/7774e08c-6b50-48ee-ba8b-05d5b0fb7e48)

I think it's a protection from microsoft for device search...

Got the same on other script
