### ISSUE TITLE
how to bypass google in certain country

### ISSUE THREAD

**Issue by cmulittlechild** [TheNetsky/Microsoft-Rewards-Script#32]
can you just give an alternative file which we can choose containing different words but not get the words for searching task from google, you know sometimes, some countries' internet is not very well, they can not get to the google.

Additionly, at this picture, what should i do? i confirm the permisson on my phone, then i just wait? or i should put in something on console?
<img width="546" alt="iShot_2024-01-02_01 25 46" src="https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/31565938/fea9d1d1-13e3-44ab-ab3c-480b9c87331f">

**Comment by cmulittlechild** [comment]
just like it, i can not get google
<img width="567" alt="image" src="https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/31565938/5d3f9793-c919-4fc0-9597-db35b3924890">

**Comment by TheNetsky** [comment]
I do not have plans in removing google trends. You're free to make those changes if you so desire. The 2FA is only for SMS authentication, else disables headless and login manually.

**Comment by cmulittlechild** [comment]
> I do not have plans in removing google trends. You're free to make those changes if you so desire. The 2FA is only for SMS authentication, else disables headless and login manually.

all right, no matter what, thanks for your job！
