### ISSUE TITLE
browser stuck

### ISSUE THREAD

**Issue by saurabh9661180** [TheNetsky/Microsoft-Rewards-Script#33]
sometimes browser stuck and please add skip suspended acc and continue other account
and maybe if possible add log file so completed acc dont launch again

**Comment by TheNetsky** [comment]
Just remove the blocked account? Also more info on the other issue.

**Comment by saurabh9661180** [comment]
[3/1/2024, 9:54:17 pm] [PID: 2496] [LOG] [GO-HOME] Visited homepage successfully
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [TypeError]: Cannot read properties of undefined (reading 'log')

**Comment by TheNetsky** [comment]
Cannot replicate.

**Comment by saurabh9661180** [comment]
> Cannot replicate.

sir please look into this browser always stuck at this pager after sometime 
![Screenshot (33)](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/84256030/9ad6c87b-079a-4213-8b49-e279bc854cd3)

**Comment by TheNetsky** [comment]
Should be fixed in upcoming version.

**Comment by saurabh9661180** [comment]
> Should be fixed in upcoming version.

Thank you so much
