### ISSUE TITLE
Docker Run Command?

### ISSUE THREAD

**Issue by royaltongue** [TheNetsky/Microsoft-Rewards-Script#38]
Besides building the Dockerfile, could you provide what other docker settings are needed to get this up and running?

**Comment by TheNetsky** [comment]
`docker build -t microsoft-rewards-script-docker .`
It's fairly untested yet

**Comment by mgrimace** [comment]
Hi, sorry to revive this, after building you have to run the docker image that you built, for example `docker run --name netsky -d microsoft-rewards-script-docker` would run this as a container called `netsky`. You can change the name to anything you want, you can also remove the detached flag `-d` to view what's actually happening when it runs.
