### ISSUE TITLE
Unable to complete searches 

### ISSUE THREAD

**Issue by Kraker01** [TheNetsky/Microsoft-Rewards-Script#39]
Hi,
i'm using latest version (just reinstalled from scratch) and i'm experiencing errors while doing searches:

"[16/1/2024, 16:52:30] [PID: 12712] [ERROR] [SEARCH-BING] Search failed, An error occurred:Error: page.waitForSelector: Timeout 10000ms exceeded.
Call log:
  - waiting for locator('#sb_form_q')"

I'm having this problem only in one account while other 2 are not experiencing errors

**Comment by TheNetsky** [comment]
I'll check it out, have not had this issue

**Comment by TheNetsky** [comment]
Hopefully fixed in 1.4.2
