### ISSUE TITLE
This error message appears when npm start run is executed.

### ISSUE THREAD

**Issue by Chappie18** [TheNetsky/Microsoft-Rewards-Script#4]
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/67442659/7c04d35c-351d-4335-9746-8aa68c348f5e)
not sure how to troubleshoot, could you please assist me?

**Comment by TheNetsky** [comment]
Show config.json

**Comment by Chappie18** [comment]
> Show config.json

![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/67442659/f7be9c90-ff1f-4618-a604-ce766b6cd9af)
here it is

**Comment by TheNetsky** [comment]
Interesting, I'll look at it later, are you sure the config.json is present and valid in the "dist" folder?

**Comment by Chappie18** [comment]
> Interesting, I'll look at it later, are you sure the config.json is present and valid in the "dist" folder?

![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/67442659/a807c64a-60ce-4c23-a74c-c79b94e72677)
Yes it is present there.

**Comment by Chappie18** [comment]
> I cannot replicated this.
> 
> I've tried
> 
> 1. `npm i` (Installs packages)
> 2. `npm run build` (Builds successfully)
> 3. `npm run start` (Start script normally, no errors)
> 
> All done from the root folder.

i had node.js installed before, would that be causing issues?

**Comment by Chappie18** [comment]
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/67442659/1a3ce6b5-3b75-4bf5-93c3-4078de86b14a)
Lmao this was causing the error .

**Comment by Chappie18** [comment]
> Don't leak your stuff, glad you've found the issue.

changed credentials before to submitting, and I appreciate your help.
