### ISSUE TITLE
browser

### ISSUE THREAD

**Issue by saurabh9661180** [TheNetsky/Microsoft-Rewards-Script#45]
only first account open in desktop mode then after every account launch with mobile mode because its only do mobile searches
but in cmd shows created desktop browser

**- `[18/1/2024, 4:38:54 pm] [PID: 17952] [LOG] [MAIN] Starting DESKTOP browser
- [18/1/2024, 4:39:13 pm] [PID: 17952] [LOG] [LOGIN] Already logged in
- [18/1/2024, 4:39:13 pm] [PID: 17952] [LOG] [LOGIN-BING] Verifying Bing login
- [18/1/2024, 4:39:21 pm] [PID: 17952] [LOG] [LOGIN-BING] Bing login verification passed!
- [18/1/2024, 4:39:21 pm] [PID: 17952] [LOG] [LOGIN] Logged in successfully
- [18/1/2024, 4:39:31 pm] [PID: 17952] [LOG] [GO-HOME] Visited homepage successfully
- [18/1/2024, 4:39:33 pm] [PID: 17952] [LOG] [MAIN-POINTS] Current point count: 996
- [18/1/2024, 4:39:34 pm] [PID: 17952] [LOG] [MAIN-POINTS] You can earn 150 points today
- [18/1/2024, 4:39:41 pm] [PID: 17952] [LOG] [GO-HOME] Visited homepage successfully
- [18/1/2024, 4:39:41 pm] [PID: 17952] [LOG] [DAILY-SET] All Daily Set" items have already been completed
- [18/1/2024, 4:39:41 pm] [PID: 17952] [LOG] [SEARCH-BING] Starting bing searches
- [18/1/2024, 4:39:43 pm] [PID: 17952] [LOG] [SEARCH-GOOGLE-TRENDS] Generating search queries, can take a while! | GeoLocale: IN
- [18/1/2024, 4:39:48 pm] [PID: 17952] [LOG] [SEARCH-BING] 60 Points Remaining | Query: ms dhoni | Mobile: true
- [18/1/2024, 4:39:55 pm] [PID: 17952] [LOG] [SEARCH-BING] 60 Points Remaining | Query: davos | Mobile: true
- [18/1/2024, 4:40:03 pm] [PID: 17952] [LOG] [SEARCH-BING] 60 Points Remaining | Query: samsung s24 | Mobile: true
- [18/1/2024, 4:40:13 pm] [PID: 17952] [LOG] [SEARCH-BING] 51 Points Remaining | Query: nz vs pak | Mobile: true`**

**Comment by saurabh9661180** [comment]
it is creating Desktop browser with mobile useragent

**Comment by TheNetsky** [comment]
Cannot replicated, maybe someone else can. Until then will not really do anything about this.

**Comment by luxcas0212** [comment]
I'm also having this problem, but I ran the whole script again at the end and it works normally

**Comment by TheNetsky** [comment]
> I'm also having this problem, but I ran the whole script again at the end and it works normally

You have this problem but it works normally? Then what is the problem?

Please provide logs.

**Comment by TheNetsky** [comment]
Should be fixed with 1.4.3.
