### ISSUE TITLE
Syntax for Sending message to Telegram Bot 

### ISSUE THREAD

**Issue by Chappie18** [TheNetsky/Microsoft-Rewards-Script#5]
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/67442659/d6ed897e-5bc5-4196-b1ea-30efadbe8f7e)
Tried using this but failed to send message to telegram.

**Comment by TheNetsky** [comment]
It's meant for Discord, not Telegram.

**Comment by Chappie18** [comment]
> It's meant for Discord, not Telegram.
A tiny request: Could you perhaps add support for Telegram and the live message feature in the future :)

**Comment by TheNetsky** [comment]
Make a PR which such, I have no intention in adding that since I do not have and use Telegram.
