### ISSUE TITLE
Take The Tour

### ISSUE THREAD

**Issue by saurabh9661180** [TheNetsky/Microsoft-Rewards-Script#50]
"Take the tour". This promotion is causing urlReward to be stuck.

**Comment by TheNetsky** [comment]
I'm not implementing that, I'd recommend to just do that one yourself. It's a one time thing.

**Comment by saurabh9661180** [comment]
> I'm not implementing that, I'd recommend to just do that one yourself. It's a one time thing.

oo then its fine  i can do that while creating account
