### ISSUE TITLE
Crash on browser error

### ISSUE THREAD

**Issue by 0belous** [TheNetsky/Microsoft-Rewards-Script#52]
OS: Windows 10 19045
Node: 18.18.2 (LTS)

The script doesn't like when bing returns an error 500.
With headless disabled I can see the error screen flash before it crashes.
Microsoft also gives me a 500 after signing in which i can just refresh manually then the script keeps going.

```
[21/01/2024, 13:16:33] [PID: 12944] [LOG] [MAIN] Starting DESKTOP browser
[21/01/2024, 13:16:54] [PID: 12944] [LOG] [LOGIN] Email entered successfully
[21/01/2024, 13:16:56] [PID: 12944] [LOG] [LOGIN] Password entered successfully
[21/01/2024, 13:17:38] [PID: 12944] [LOG] [LOGIN] Logged into Microsoft successfully
[21/01/2024, 13:17:38] [PID: 12944] [LOG] [LOGIN-BING] Verifying Bing login
[21/01/2024, 13:17:41] [PID: 12944] [LOG] [LOGIN-BING] Bing login verification passed!
[21/01/2024, 13:17:41] [PID: 12944] [LOG] [LOGIN] Logged in successfully
[21/01/2024, 13:17:51] [PID: 12944] [LOG] [GO-HOME] Visited homepage successfully
[21/01/2024, 13:17:53] [PID: 12944] [LOG] [MAIN-POINTS] Current point count: 1285
[21/01/2024, 13:17:54] [PID: 12944] [ERROR] [GET-EARNABLE-POINTS] An error occurred:Error: page.evaluate: Execution context was destroyed, most likely because of a navigation
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.18.2
```

**Comment by TheNetsky** [comment]
Having the same issue, MS likely changed something. Not gonna have time to fix this for a bit.

**Comment by luxcas0212** [comment]
I realized that the error has to do with some connection block, whenever this error occurs, in the browser the connection is blocked, showing an http error "bing.com cannot fulfill this request at the moment." http404, so if you refresh the page it loads normally, but sometimes it needs to be reloaded 3 times or more, when I'm fast enough the script keeps working

**Comment by luxcas0212** [comment]
![Screenshot 2024-01-21 122007](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/111216339/1b075419-cecc-4323-9340-8c62a49205c8)

maybe it's just a problem with microsoft's servers, when I run it in chrome or in an anonymous tab the error occurs, it just doesn't occur when I'm logged into microsoft edge

**Comment by luxcas0212** [comment]
I've tried using my 4g internet and another wifi and the error is always displayed on all my accounts, either it's a server error or all the accounts have been "banned"

**Comment by luxcas0212** [comment]
I changed the baseurl to the url that was shown on the edge "https://rewards.bing.com/?form=dash_2", I don't know what this changes but apparently the http error now occurs less frequently, the script was able to proceed
![Screenshot 2024-01-21 124008](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/111216339/841d4fbe-9bf5-4d56-8d59-c6d7ea9c6e6a)

**Comment by saurabh9661180** [comment]
> ![Screenshot 2024-01-21 122007](https://private-user-images.githubusercontent.com/111216339/298392716-1b075419-cecc-4323-9340-8c62a49205c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NTQ4NzcsIm5iZiI6MTcwNTg1NDU3NywicGF0aCI6Ii8xMTEyMTYzMzkvMjk4MzkyNzE2LTFiMDc1NDE5LWNlY2MtNDMyMy05MzQwLThjNjJhNDkyMDVjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMVQxNjI5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2EzZjVjM2E2YjEyNWM0NThjZjA0MGIyMGFlYThiNzAyNGY0YmE1NWY3OTQ1MTcxOGRlNjQ0M2ZlY2UyOGM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iYLGNFmsaNn9W5wHqg7Bc0mBqVBiB7xSfqqi_LLyJjw)
> 
> maybe it's just a problem with microsoft's servers, when I run it in chrome or in an anonymous tab the error occurs, it just doesn't occur when I'm logged into microsoft edge

same issue

**Comment by luxcas0212** [comment]
I didn't get the error today, probably the connection problem is solved

**Comment by TheNetsky** [comment]
Same, was likely something on MS's end.

**Comment by saurabh9661180** [comment]
> Same, was likely something on MS's end.

any cooldown theory you have ? why i am getting cooldown issue ?
