### ISSUE TITLE
Automatic acceptance of cookies

### ISSUE THREAD

**Issue by Crover81** [TheNetsky/Microsoft-Rewards-Script#53]
I encounter this problem, when the program opens a daily card, if I don't press "Accetta" (Accept cookies) it doesn't proceed and moves on to the next daily card, once accepted the program proceeds regularly until it is reopened. what can I do? Thank you.

![bug](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/84338382/9c85fc4a-ee00-468e-b15f-8ca9908077f9)

**Comment by TheNetsky** [comment]
I've not encountered this. Not sure what's causing it.

**Comment by TheNetsky** [comment]
Fixed in 1.4.4, hopefully.
