### ISSUE TITLE
Time search

### ISSUE THREAD

**Issue by basalisco** [TheNetsky/Microsoft-Rewards-Script#58]
For a few days the script has not respected the minimum search time. Currently set to 300000 but from the logs barely 1 minute passes between one search and another.

**Comment by TheNetsky** [comment]
You must change the `config.json` in `src/config.json` then rebuild the script.
Alternatively change the `config.json` in the `dist` folder.

**Comment by basalisco** [comment]
> You must change the `config.json` in `src/config.json` then rebuild the script. Alternatively change the `config.json` in the `dist` folder.

```
[2/2/2024, 01:04:06] [PID: 461] [LOG] [SEARCH-BING] 36 Points Remaining | Query: djokovic | Mobile: false
[2/2/2024, 01:05:21] [PID: 461] [LOG] [SEARCH-BING] 36 Points Remaining | Query: panatta | Mobile: false
[2/2/2024, 01:06:37] [PID: 461] [LOG] [SEARCH-BING] 36 Points Remaining | Query: alcaraz | Mobile: false
```
and is the config.json in dist folder

```
{
    "baseURL": "https://rewards.bing.com",
    "sessionPath": "sessions",
    "headless": true,
    "runOnZeroPoints": false,
    "clusters": 4,
    "saveFingerprint": true,
    "workers": {
        "doDailySet": true,
        "doMorePromotions": true,
        "doPunchCards": true,
        "doDesktopSearch": true,
        "doMobileSearch": true
    },
    "searchSettings": {
        "useGeoLocaleQueries": true,
        "scrollRandomResults": true,
        "clickRandomResults": true,
        "searchDelay": {
            "min": 300000,
            "max": 600000
        },
        "retryMobileSearch": true
    },
    "webhook": {
        "enabled": false,
        "url": ""
    }
}
```
I think it could be related to the maximum load of processes on the cpu or ram

**Comment by TheNetsky** [comment]
Gonna be hard for me to debug this, since I only use 1 account. On which I cannot replicate this issue. I'll reopen it for someone else to maybe look at.

**Comment by luxcas0212** [comment]
I have several accounts and I also have this problem, the solution here was to create another bot instance, divide the accounts between them and set the clusters to 1
