### ISSUE TITLE
Fingerprint

### ISSUE THREAD

**Issue by iFredOS** [TheNetsky/Microsoft-Rewards-Script#67]
Hi, sorry this is not an issue but more a question, because I cannot ask it elsewhere.

I understand mostly your script except the part about "Fingerprint". Can you explain the use, the purpose to save or not the "Fingerprint"?

Thanks 😄

**Comment by TheNetsky** [comment]
It's a "Browser Fingerprint" you can choose to keep the same one, so it seems like it's the same device doing the tasks, or choose not to save them so it looks a different device is doing the task each time the script is ran.
