### ISSUE TITLE
Bot very slow

### ISSUE THREAD

**Issue by MacMarde** [TheNetsky/Microsoft-Rewards-Script#68]
Hi I just tested your bot.

It seems like many websites are very slow loading (several minutes) with permanent high cpu usage for no obvious reason.

I also started the bot in debug mode and then paused it directly before logging in, because I wanted to create a new account.
Unfortunately the funcaptcha is not working and also loading endless times with high cpu usage.

Maybe there is something not working like it should?

**Comment by TheNetsky** [comment]
Don't use the bot to make accounts etc, do it yourself and then provide the login info to the bot. I cannot replicate the high CPU usage myself. But it's using chrome so it's high usage in general.

**Comment by MacMarde** [comment]
@TheNetsky 
How about redeeming?
Also not in the bot?
What is your recommanded way to redeem?

**Comment by TheNetsky** [comment]
I'm not adding redeeming, I just redeem normally. To each their own, also depends on how many accounts you're using.

Otherwise use another bot for redeeming.
