### ISSUE TITLE
Github Taking Action on similar repositories.

### ISSUE THREAD

**Issue by JittoJoseph** [TheNetsky/Microsoft-Rewards-Script#72]
Since Github has been banning many accounts that are currently developing software to automate microsoft rewards, maybe you should start a discord server as backup, or even move this whole project to gitlab.

**Comment by TheNetsky** [comment]
And were is proof of this?

**Comment by JittoJoseph** [comment]
https://gitlab.com/farshadzargary1997/Microsoft-Rewards-bot
this project was previously on github, it was very active, then the repo got taken down and he moved it to gitlab,
i was mistaken that they ban accounts.
i have noticed them taking action on repos that promote rewards automation and is active,
they dont seem to care about archived repos and projects that were discontinued.

**Comment by JittoJoseph** [comment]
here is a link to the old repo on github https://github.com/farshadz1997/Microsoft-Rewards-bot

you can see that it says This repository has been disabled.
Access to this repository has been disabled by GitHub Staff due to a violation of GitHub's terms of service. If you are the owner of the repository, you may reach out to GitHub Support for more information.

**Comment by TheNetsky** [comment]
If that was true, then why is the main repo still fine?
https://github.com/charlesbel/Microsoft-Rewards-Farmer

**Comment by JittoJoseph** [comment]
i'm not sure,
just thought i should give a heads up.
can close this issue now.
