### ISSUE TITLE
Facing this error 

### ISSUE THREAD

**Issue by Chappie18** [TheNetsky/Microsoft-Rewards-Script#8]
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/67442659/af50b22c-3343-4c3d-8a5d-92522d0d6787)
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/67442659/c77585aa-dad7-4933-8007-50b1a47dcfef)

**Comment by TheNetsky** [comment]
Just seems like a timeout, likely something on your side. That error is a normal error when either your internet or the page takes longer than 10 seconds to respond.

**Comment by Chappie18** [comment]
The issue arose after Chrome switched to a new version from 117 to 118, resulting in difficulties with old session data.
