### ISSUE TITLE
Automatic acceptance of cookies on mobile

### ISSUE THREAD

**Issue by serzak51** [TheNetsky/Microsoft-Rewards-Script#82]
related to https://github.com/TheNetsky/Microsoft-Rewards-Script/issues/53 ,while it seems fixed on desktop, on mobile it's often (if not everytime) that the window is popping up and not closing, generating errors for searches

**Comment by TheNetsky** [comment]
I'm unable to replicate this. works fine on my end.

**Comment by serzak51** [comment]
It seems to happen the first time the account is ran. After accepting the cookie, it works fine (for refusing however it seems to keep asking? Might be placebo though). I thought it was only for mobile cookies, but it seems to also happen for desktop cookies. I have saveFingerprint on true, though i'm not sure if it's related.
