### ISSUE TITLE
30 points are not claimed

### ISSUE THREAD

**Issue by TrinitroToluen0** [TheNetsky/Microsoft-Rewards-Script#84]
I saw this message in the console with each account:

"You can earn 30 points today"

And these 30 points were never claimed even if I restart the script. I logged into these accounts and noticed that there were no tasks to do and all the searches were already done. So I thought it was just a bug in the counting of earnable points.

My accounts were earning around 240 points every day, but after this message appeared it was only 210. I started investigating and it seems that these 30 points were real, but they don't appear on the rewards.bing.com page:
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/92131917/70e8e50a-a4ee-4376-a383-3200949d138c)

But if I go to the Bing search engine, click on the "medal" icon and show the rewards panel, the 30 points are there in 3 tasks where each one gives you 10 points:
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/92131917/834ebea0-1e93-4881-aec2-dc77cf209115)

These 3 tasks can be done manually, so I don't know why they don't appear in the main tab.

**Comment by TrinitroToluen0** [comment]
Also, when inspecting the elements for more information, I noticed that in the link they have text like "Gamification_dailyset", which definitely has something to do with this other error in the console.

![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/92131917/124c1c5d-d8ea-4ed2-a5ce-c60a7d12623a)
![image](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/92131917/7ce8bbb6-f858-414b-a342-b77546f13f5b)

**Comment by TheNetsky** [comment]
Rerun the script again

**Comment by TrinitroToluen0** [comment]
> And these 30 points were never claimed even if I restart the script.

**Comment by TheNetsky** [comment]
Likely those tasks are not support by the script.

**Comment by TrinitroToluen0** [comment]
I see
