### ISSUE TITLE
The "path" argument must be of type string.

### ISSUE THREAD

**Issue by xunilalala** [TheNetsky/Microsoft-Rewards-Script#95]
I'm using version microsoft-rewards-script@1.4.5, and I've done a correct npm install. However, the terminal is returning me this error:
<hr/>
D:\SoftWare\Node\npm.cmd run start

\> microsoft-rewards-script@1.4.5 start
\> node ./dist/index.js

[2024/4/18 21:35:43] [PID: 12772] [LOG] [MAIN] Bot started with 1 clusters
[2024/4/18 21:35:43] [PID: 12772] [LOG] [MAIN-WORKER] Started tasks for account undefined
D:\Downloads\Microsoft-Rewards-Script-main\dist\util\Load.js:58
        throw new Error(error);
              ^

Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at loadSessionData (D:\Downloads\Microsoft-Rewards-Script-main\dist\util\Load.js:58:15)
    at Browser.createBrowser (D:\Downloads\Microsoft-Rewards-Script-main\dist\browser\Browser.js:33:62)
    at async MicrosoftRewardsBot.Desktop (D:\Downloads\Microsoft-Rewards-Script-main\dist\index.js:99:25)
    at async MicrosoftRewardsBot.runTasks (D:\Downloads\Microsoft-Rewards-Script-main\dist\index.js:83:13)

Node.js v18.12.0
<hr/>
I'd like to ask what's going on and how to fix it.

>  Additionally, I've also tried the Docker version of this release, but I'm still encountering the same error.

**Comment by Oussema-Hakim** [comment]
> Try to delete your session files. From what i understand it fails at loading a sessiondata, maybe one is corrupted

i m having the same issue , i also tried using docker , the problem is i looked for the session files but i can't seem to find them 
and in the docker version it doesn't make sense for the session files to be corrupted as i just built the container

**Comment by Titaniumtown** [comment]
This is something I'm facing on both the main branch and 1.5. I cannot fix it. Even from a fresh git clone. Please help!

**Comment by tusharbhatte** [comment]
> machine translation

@Titaniumtown  It's been so long that I almost forgot I was the one who raised this issue. Back then, I was in the same situation as you, and updating the Git repository didn't work. The final solution was to download a new zip file from GitHub, extract it to a brand-new location, move the account.json file into it, and then the problem was resolved.

**Comment by TheNetsky** [comment]
Show config.json
