### ISSUE TITLE
Puzzle daily activity

### ISSUE THREAD

**Issue by jordyamc** [TheNetsky/Microsoft-Rewards-Script#97]
The puzzle activity can be omitted with a button (upper right corner), I think it can be automated

**Comment by TheNetsky** [comment]
There's no such activity in my region.

**Comment by jordyamc** [comment]
I can provide links and the HTML code of the puzzle

The activity url looks like this:
`https://www.bing.com/spotlight/imagepuzzle?form=ML2BF0&OCID=ML2BF0&PUBL=RewardsDO&PROGRAMNAME=BingDailyOfferIN&CREA=ML2BF0`

Here's the activity:
![SS 2024-04-20 160616](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/6831873/d3cb6ad5-89be-4414-81c1-a59840dd24df)

This is how it looks:
![SS 2024-04-20 160533](https://github.com/TheNetsky/Microsoft-Rewards-Script/assets/6831873/d5c5c3f6-6313-477e-a21e-4aac9367fb76)

The upper right button skips the activity and gives you the points, the html code of the button looks like this:
```html
<div class="skipPuzzle" id="skipPuzzle">
   <a target="_blank" href="https://www.bing.com/ck/a?!&amp;&amp;p=9950f104e2ba823bJmltdHM9MTcxMzU3MTIwMCZpZ3VpZD0zOGUzMGMzMy02ZjE0LTY4NDItMTQ5Ny0xODUzNmU3NzY5NDImaW5zaWQ9NTA0NQ&amp;ptn=3&amp;ver=2&amp;hsh=3&amp;fclid=38e30c33-6f14-6842-1497-18536e776942&amp;u=a1aHR0cHM6Ly93d3cuYmluZy5jb20vc3BvdGxpZ2h0P3E9QmFueXV3YW5naUluZG9uZXNpYSZzcG90bGlnaHRJZD1CYW55dXdhbmdpSW5kb25lc2lhJkZPUk09bWwyYmYw&amp;ntb=1" h="ID=SERP,5045.2">
      <div>Omitir rompecabezas</div>
   </a>
</div>
```

And here's the html code:
[Puzzle.zip](https://github.com/TheNetsky/Microsoft-Rewards-Script/files/15049877/Puzzle.zip)

**Comment by TheNetsky** [comment]
Well, untill the puzzle is in my region, I won't be adding support for it. However feel free to submit a PR yourself if you're feeling up for it.

**Comment by xunilalala** [comment]
> 拼图活动可以用按钮（右上角）省略，我认为它可以自动化

### Completing the puzzle is not the criterion for finishing the activity! 
I am a user of Bing in China. I also have this puzzle activity, but the condition for completing it is not finishing the puzzle. Simply opening the activity and then closing the window (I cannot guarantee that closing this action will not affect the completion judgment) will suffice for completion. The existing bots are capable of completing this activity and will take less time.

**Comment by jordyamc** [comment]
> but the condition for completing it is not finishing the puzzle
I did some tests and the activity didn't shows as completed until the puzzle is solved or when the skip button is clicked, I already did the code necessary to complete the puzzle (At lease I hope so, I have never worked with Playwright) but unfortunately the puzzle activity is not showing for me today so I can't test it

**Comment by serzak51** [comment]
Yeah, me too, simply opening and closing the activity seems to work. Maybe it's region related, in some region it check if the puzzle was made/skipped, in others they don't bother with it

**Comment by xunilalala** [comment]
> > but the condition for completing it is not finishing the puzzle
> 
> I did some tests and the activity didn't shows as completed until the puzzle is solved or when the skip button is clicked, I already did the code necessary to complete the puzzle (At lease I hope so, I have never worked with Playwright) but unfortunately the puzzle activity is not showing for me today so I can't test it

My region is China, and my jigsaw puzzle activity has indeed been completed by a bot (without my manual participation throughout the process). Perhaps, as @serzak51 mentioned, your region may have its own set of detection methods.

**Comment by TheNetsky** [comment]
In that case make your modifications to a fork of this repo.

**Comment by OwnerCM** [comment]
> > 拼图活动可以用按钮（右上角）省略，我认为它可以自动化
> 
> ### Completing the puzzle is not the criterion for finishing the activity!
> I am a user of Bing in China. I also have this puzzle activity, but the condition for completing it is not finishing the puzzle. Simply opening the activity and then closing the window (I cannot guarantee that closing this action will not affect the completion judgment) will suffice for completion. The existing bots are capable of completing this activity and will take less time.
How to set TZ for Chinese users? Also what other configurations need to be changed?
I'm currently configured for New York, but I can't redeem points for domestic gifts.

**Comment by OwnerCM** [comment]
> @OwnerCM I'm sorry to inform you that it’s best not to become a Chinese user. Since around September 2024 (I'm not sure of the exact date), for Chinese users of the reward , it’s required that the account has not been used to manipulate points in other regions. Otherwise, the account will be immediately banned. This is usually indicated by a constant message on the reward interface saying "It seems like you are traveling." Therefore, if you do want to use the Chinese region, please use a Chinese proxy to register a new account, bind it to the corresponding phone number, and consistently use a clean proxy. Also, avoid activating the reward immediately; instead, wait for two to three weeks.

@xunilalala  I'm in China myself and only Chinese gifts are suitable for me, should I set the TZ to Beijing, China or Hong Kong, China in this case?

**Comment by xunilalala** [comment]
@OwnerCM  不是哥们,这个东西吧,时区无所谓,具体的判断逻辑都在微软那边,你的时区仅仅影响你本地机器的的计算和显示,和reward没有任何关系, 你如果想说的是你的地区是纽约而不是国内,那我只能说你用了代理,够呛能兑换国内的了,如果还有别的这方面的问题,麻烦发我邮箱,不要这个问题下讨论,他已经偏题了  xuni1024@outlook.com
